version: "3.2"

services:
  yt-fake-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yt-fake-backend
    volumes:
      - "./backend:/home/node/app"
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:12.10
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "database:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: yt_fake

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  database:
    external: true
