name: Continuous integration and continuous deployment

on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, reopened]
    branches: [main, master]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Rename .env.example
        run: cp .env.example .env

      - name: Run all test
        run: npm run test:ci

      - name: Run mutation test
        run: npm run test:mutation
  # CD:
  #   needs: [CI]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Deploy application
  #       if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
  #       uses: akhileshns/heroku-deploy@v3.12.12
  #       with:
  #         heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
  #         heroku_app_name: 'yt_fake'
  #         heroku_email: ${{ secrets.HEROKU_EMAIL }}
