name: Continuous integration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: Install Docker Compose
      #   run: docker-compose
      # - name: Install Docker Compose
      #   uses: ndeloof/install-compose-action@v0.0.1
      #   with:
      #     version: v2.9.0
      #     legacy: true

      - name: Copy .env
        run: cp .env.example .env

      - name: Start app
        run: make start-app

      # - name: Run lint
      #   run: make lint

      - name: Run all test
        run: docker-compose run yt-fake-backend npm run dev

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
