name: Continuous integration and continuous deployment

on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, reopened]
    branches: [main, master]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Install Docker Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.9.0
          legacy: true

      - name: Start app
        run: make start-app

      - name: Run lint
        run: make lint

      - name: Run all test
        run: make test

      - name: Run mutation test
        run: make test-mutation

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # CD:
  #   needs: [CI]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Deploy application
  #       if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
  #       uses: akhileshns/heroku-deploy@v3.12.12
  #       with:
  #         heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
  #         heroku_app_name: 'yt_fake'
  #         heroku_email: ${{ secrets.HEROKU_EMAIL }}
